flagception:
    features:
        photos:
            default: true
        art11:
            default: false
        frontpage_advertisment:
            default: false
        oembed:
            default: true
