fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\User
    registration:
        confirmation:
            enabled:    true
            from_email:
                address:        malte@caldera.cc
                sender_name:    Malte Hübner, criticalmass.in
        form:
            type: App\Form\Type\RegistrationType
    resetting:
        email:
            from_email:
                address:        malte@caldera.cc
                sender_name:    Malte Hübner, criticalmass.in
    from_email:
        address:        malte@caldera.cc
        sender_name:    Malte Hübner, criticalmass.in
    service:
        mailer: App\Criticalmass\Mailer\MailHandler
