hwi_oauth:
    firewall_names: ['main']

    resource_owners:
        facebook:
            type:                facebook
            client_id:           '%facebook.app_id%'
            client_secret:       '%facebook.app_secret%'
            scope:               email
            infos_url:           https://graph.facebook.com/me?fields=id,name,email,first_name,last_name,gender
        strava:
            type:                strava
            client_id:           '%strava.client_id%'
            client_secret:       '%strava.secret%'
        twitter:
            type:                twitter
            client_id:           '%twitter.client_id%'
            client_secret:       '%twitter.secret%'
