###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:
  memcached:
    image: memcached:alpine
    container_name: criticalmass-memcached
    labels:
      com.symfony.server.service-prefix: 'MEMCACHED'

  redis:
    image: redis:alpine
    container_name: criticalmass-redis
    labels:
      com.symfony.server.service-prefix: 'REDIS'

  mysql:
    image: mariadb:10.3.25
    command: --default-authentication-plugin=mysql_native_password
    container_name: criticalmass-mysql
    working_dir: /application
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=criticalmass
      - MYSQL_USER=criticalmass
      - MYSQL_PASSWORD=criticalmass
    ports:
      - "8002:3306"
    labels:
      com.symfony.server.service-prefix: 'DATABASE'

  elasticsearch:
    image: elasticsearch:7.17.8
    container_name: criticalmass-elasticsearch
    environment:
      - discovery.type=single-node
      - cluster.routing.allocation.disk.threshold_enabled=true
      - cluster.routing.allocation.disk.watermark.flood_stage=100mb
      - cluster.routing.allocation.disk.watermark.low=500mb
      - cluster.routing.allocation.disk.watermark.high=250mb
    volumes:
      - ./docker/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    labels:
      com.symfony.server.service-prefix: 'ELASTICSEARCH'