<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Meldungen zu Beitraegen, samt der Entscheidung darueber.
 *
 * Wird ein Beitrag geloescht, gehen seine Meldungen mit (CASCADE). Wird ein
 * Konto geloescht, bleibt die Meldung stehen und verliert nur den Verweis
 * (SET NULL) — die Entscheidung muss nachvollziehbar bleiben.
 *
 * Die CHECKs halten die Werte deckungsgleich mit PostReportReasonEnum und
 * PostReportStatusEnum, wie post_kind_check beim PostKindEnum.
 */
final class Version20261006150000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add post_report';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("CREATE TABLE post_report (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, reporterEmail VARCHAR(255) DEFAULT NULL, reason VARCHAR(16) NOT NULL, explanation TEXT DEFAULT NULL, createdAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(16) DEFAULT 'OPEN' NOT NULL, decidedAt TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, decisionNote TEXT DEFAULT NULL, post_id INT NOT NULL, reporter_id INT DEFAULT NULL, decided_by_id INT DEFAULT NULL, PRIMARY KEY (id))");
        $this->addSql('CREATE INDEX IDX_F40D93E14B89032C ON post_report (post_id)');
        $this->addSql('CREATE INDEX IDX_F40D93E1E1CFE6F5 ON post_report (reporter_id)');
        $this->addSql('CREATE INDEX IDX_F40D93E1E26B496B ON post_report (decided_by_id)');
        $this->addSql('CREATE INDEX post_report_status_index ON post_report (status)');
        $this->addSql('ALTER TABLE post_report ADD CONSTRAINT FK_F40D93E14B89032C FOREIGN KEY (post_id) REFERENCES post (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE post_report ADD CONSTRAINT FK_F40D93E1E1CFE6F5 FOREIGN KEY (reporter_id) REFERENCES app_user (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE post_report ADD CONSTRAINT FK_F40D93E1E26B496B FOREIGN KEY (decided_by_id) REFERENCES app_user (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql("ALTER TABLE post_report ADD CONSTRAINT post_report_reason_check CHECK (reason IN ('ILLEGAL', 'HARASSMENT', 'PRIVACY', 'SPAM', 'OTHER'))");
        $this->addSql("ALTER TABLE post_report ADD CONSTRAINT post_report_status_check CHECK (status IN ('OPEN', 'REMOVED', 'DISMISSED'))");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE post_report');
    }
}
