<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Ausgangspunkt der Migrationsgeschichte.
 *
 * Die 119 Migrationen davor waren MySQL-only; 97 von ihnen riefen
 * $this->connection->getDatabasePlatform()->getName() auf, eine Methode, die es
 * seit DBAL 4 nicht mehr gibt. Die Kette liess sich damit ohnehin nicht mehr von
 * null abspielen. Sie bleibt in der Git-Historie erhalten.
 *
 * Seit dem Umzug am 2026-09-05 beschreibt diese Datei das Schema **fuer
 * PostgreSQL**. Die MySQL-Fassung steht in der Git-Historie; sie wieder zu
 * brauchen hiesse, den Umzug rueckgaengig zu machen, und dafuer gibt es die
 * bestehende MySQL-Datenbank, nicht diese Migration.
 *
 * Auf einer bestehenden Datenbank wird sie nicht ausgefuehrt, sondern als
 * erledigt eingetragen:
 *
 *   bin/console doctrine:migrations:version --add \
 *       'DoctrineMigrations\Version20260904120000' --no-interaction
 */
final class Version20260904120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Baseline: legt das vollstaendige Schema mit 31 Tabellen an (PostgreSQL)';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform,
            'Diese Baseline beschreibt das Schema fuer PostgreSQL. criticalmass.in ist am '
            . '2026-09-05 dorthin umgezogen; eine MySQL-Fassung wird nicht mehr gepflegt.'
        );

        $this->addSql('CREATE TABLE city (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, city VARCHAR(50) DEFAULT NULL, title VARCHAR(100) DEFAULT NULL, description TEXT DEFAULT NULL, latitude DOUBLE PRECISION DEFAULT NULL, longitude DOUBLE PRECISION DEFAULT NULL, enabled BOOLEAN DEFAULT NULL, cityPopulation INT DEFAULT NULL, punchLine VARCHAR(255) DEFAULT NULL, longDescription TEXT DEFAULT NULL, imageName VARCHAR(255) DEFAULT NULL, imageSize INT DEFAULT NULL, imageMimeType VARCHAR(255) DEFAULT NULL, updatedAt TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, createdAt TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, enableBoard BOOLEAN DEFAULT NULL, timezone VARCHAR(255) DEFAULT NULL, threadNumber INT DEFAULT NULL, postNumber INT DEFAULT NULL, colorRed INT DEFAULT NULL, colorGreen INT DEFAULT NULL, colorBlue INT DEFAULT NULL, rideNamer VARCHAR(255) DEFAULT NULL, wikidataEntityId VARCHAR(255) DEFAULT NULL, activityScore DOUBLE PRECISION DEFAULT NULL, user_id INT DEFAULT NULL, region_id INT DEFAULT NULL, main_slug_id INT DEFAULT NULL, lastthread_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2D5B0234A76ED395 ON city (user_id)');
        $this->addSql('CREATE INDEX IDX_2D5B023498260155 ON city (region_id)');
        $this->addSql('CREATE INDEX IDX_2D5B0234C552CF27 ON city (main_slug_id)');
        $this->addSql('CREATE INDEX IDX_2D5B0234B43140E7 ON city (lastthread_id)');
        $this->addSql('CREATE INDEX city_created_at_index ON city (createdAt)');
        $this->addSql('CREATE TABLE region (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(255) DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, description TEXT DEFAULT NULL, wikidataEntityId VARCHAR(255) DEFAULT NULL, parent_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F62F176727ACA70 ON region (parent_id)');
        $this->addSql('CREATE TABLE ride (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(255) DEFAULT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, socialDescription TEXT DEFAULT NULL, dateTime TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, location VARCHAR(512) DEFAULT NULL, latitude DOUBLE PRECISION DEFAULT NULL, longitude DOUBLE PRECISION DEFAULT NULL, estimatedParticipants SMALLINT DEFAULT NULL, estimatedDistance DOUBLE PRECISION DEFAULT NULL, estimatedDuration DOUBLE PRECISION DEFAULT NULL, createdAt TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updatedAt TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, participationsNumberYes INT DEFAULT NULL, participationsNumberMaybe INT DEFAULT NULL, participationsNumberNo INT DEFAULT NULL, restrictedPhotoAccess BOOLEAN DEFAULT NULL, imageName VARCHAR(255) DEFAULT NULL, imageSize INT DEFAULT NULL, imageMimeType VARCHAR(255) DEFAULT NULL, enabled BOOLEAN DEFAULT true NOT NULL, disabledReason VARCHAR(255) DEFAULT NULL, rideType VARCHAR(255) DEFAULT NULL, disabledReasonMessage TEXT DEFAULT NULL, user_id INT DEFAULT NULL, cycle_id INT DEFAULT NULL, city_id INT DEFAULT NULL, featured_photo INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9B3D7CD0A76ED395 ON ride (user_id)');
        $this->addSql('CREATE INDEX IDX_9B3D7CD05EC1162 ON ride (cycle_id)');
        $this->addSql('CREATE INDEX IDX_9B3D7CD08BAC62AF ON ride (city_id)');
        $this->addSql('CREATE INDEX IDX_9B3D7CD04DFE7F82 ON ride (featured_photo)');
        $this->addSql('CREATE INDEX ride_date_time_index ON ride (dateTime)');
        $this->addSql('CREATE INDEX ride_created_at_index ON ride (createdAt)');
        $this->addSql('CREATE INDEX ride_updated_at_index ON ride (updatedAt)');
        $this->addSql('CREATE TABLE ride_estimate (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, latitude DOUBLE PRECISION DEFAULT NULL, longitude DOUBLE PRECISION DEFAULT NULL, estimatedParticipants SMALLINT DEFAULT NULL, estimatedDistance DOUBLE PRECISION DEFAULT NULL, estimatedDuration DOUBLE PRECISION DEFAULT NULL, dateTime TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, createdAt TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, source VARCHAR(255) DEFAULT NULL, user_id INT DEFAULT NULL, ride_id INT DEFAULT NULL, track_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_ADC7E493A76ED395 ON ride_estimate (user_id)');
        $this->addSql('CREATE INDEX IDX_ADC7E493302A8A70 ON ride_estimate (ride_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_ADC7E4935ED23C43 ON ride_estimate (track_id)');
        $this->addSql('CREATE INDEX ride_estimate_date_time_index ON ride_estimate (dateTime)');
        $this->addSql('CREATE TABLE location (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(255) DEFAULT NULL, latitude DOUBLE PRECISION DEFAULT NULL, longitude DOUBLE PRECISION DEFAULT NULL, title VARCHAR(255) DEFAULT NULL, description TEXT DEFAULT NULL, city_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5E9E89CB8BAC62AF ON location (city_id)');
        $this->addSql('CREATE TABLE post (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, latitude DOUBLE PRECISION DEFAULT NULL, longitude DOUBLE PRECISION DEFAULT NULL, dateTime TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, message TEXT DEFAULT NULL, updatedAt TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, enabled BOOLEAN DEFAULT NULL, parent_id INT DEFAULT NULL, user_id INT DEFAULT NULL, ride_id INT DEFAULT NULL, city_id INT DEFAULT NULL, thread_id INT DEFAULT NULL, photo_id INT DEFAULT NULL, updated_by_user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5A8A6C8D727ACA70 ON post (parent_id)');
        $this->addSql('CREATE INDEX IDX_5A8A6C8DA76ED395 ON post (user_id)');
        $this->addSql('CREATE INDEX IDX_5A8A6C8D302A8A70 ON post (ride_id)');
        $this->addSql('CREATE INDEX IDX_5A8A6C8D8BAC62AF ON post (city_id)');
        $this->addSql('CREATE INDEX IDX_5A8A6C8DE2904019 ON post (thread_id)');
        $this->addSql('CREATE INDEX IDX_5A8A6C8D7E9E4C8C ON post (photo_id)');
        $this->addSql('CREATE INDEX IDX_5A8A6C8D2793CC5E ON post (updated_by_user_id)');
        $this->addSql('CREATE INDEX post_date_time_index ON post (dateTime)');
        $this->addSql('CREATE TABLE social_network_profile (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, identifier VARCHAR(255) NOT NULL, network VARCHAR(255) NOT NULL, enabled BOOLEAN NOT NULL, createdAt TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, autoPublish BOOLEAN NOT NULL, lastFetchSuccessDateTime TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, lastFetchFailureDateTime TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, lastFetchFailureError TEXT DEFAULT NULL, autoFetch BOOLEAN NOT NULL, additionalData TEXT DEFAULT NULL, feedsProfileId INT DEFAULT NULL, user_id INT DEFAULT NULL, city_id INT DEFAULT NULL, ride_id INT DEFAULT NULL, subride_id INT DEFAULT NULL, createdBy_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3AC92AE6A76ED395 ON social_network_profile (user_id)');
        $this->addSql('CREATE INDEX IDX_3AC92AE68BAC62AF ON social_network_profile (city_id)');
        $this->addSql('CREATE INDEX IDX_3AC92AE6302A8A70 ON social_network_profile (ride_id)');
        $this->addSql('CREATE INDEX IDX_3AC92AE67B4822BF ON social_network_profile (subride_id)');
        $this->addSql('CREATE INDEX IDX_3AC92AE63174800F ON social_network_profile (createdBy_id)');
        $this->addSql('CREATE TABLE subride (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) DEFAULT NULL, description TEXT DEFAULT NULL, dateTime TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, createdAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updatedAt TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, location VARCHAR(255) DEFAULT NULL, latitude DOUBLE PRECISION DEFAULT NULL, longitude DOUBLE PRECISION DEFAULT NULL, ride_id INT DEFAULT NULL, user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_42880E5B302A8A70 ON subride (ride_id)');
        $this->addSql('CREATE INDEX IDX_42880E5BA76ED395 ON subride (user_id)');
        $this->addSql('CREATE TABLE track (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, username VARCHAR(255) DEFAULT NULL, creationDateTime TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, startDateTime TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, endDateTime TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, distance DOUBLE PRECISION DEFAULT NULL, points INT DEFAULT NULL, startPoint INT DEFAULT NULL, endPoint INT DEFAULT NULL, enabled BOOLEAN DEFAULT NULL, deleted BOOLEAN DEFAULT NULL, latLngList TEXT DEFAULT NULL, trackFilename VARCHAR(255) DEFAULT NULL, trackSize INT DEFAULT NULL, trackMimeType VARCHAR(255) DEFAULT NULL, updatedAt TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, source VARCHAR(255) DEFAULT NULL, stravaActitityId BIGINT DEFAULT NULL, reviewed BOOLEAN NOT NULL, app VARCHAR(255) DEFAULT NULL, ride_id INT DEFAULT NULL, user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D6E3F8A6302A8A70 ON track (ride_id)');
        $this->addSql('CREATE INDEX IDX_D6E3F8A6A76ED395 ON track (user_id)');
        $this->addSql('CREATE INDEX track_creation_date_time_index ON track (creationDateTime)');
        $this->addSql('CREATE TABLE board (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title TEXT DEFAULT NULL, description TEXT DEFAULT NULL, threadNumber INT DEFAULT NULL, postNumber INT DEFAULT NULL, position INT DEFAULT NULL, enabled BOOLEAN DEFAULT NULL, slug VARCHAR(255) DEFAULT NULL, lastthread_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_58562B47B43140E7 ON board (lastthread_id)');
        $this->addSql('CREATE TABLE thread (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title TEXT DEFAULT NULL, slug VARCHAR(255) DEFAULT NULL, postNumber INT DEFAULT NULL, enabled BOOLEAN DEFAULT NULL, locked BOOLEAN DEFAULT false NOT NULL, sticky BOOLEAN DEFAULT false NOT NULL, board_id INT DEFAULT NULL, city_id INT DEFAULT NULL, firstpost_id INT DEFAULT NULL, lastpost_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_31204C83E7EC5785 ON thread (board_id)');
        $this->addSql('CREATE INDEX IDX_31204C838BAC62AF ON thread (city_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_31204C83524E4EB7 ON thread (firstpost_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_31204C8338BD6675 ON thread (lastpost_id)');
        $this->addSql('CREATE TABLE city_cycle (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, dayOfWeek SMALLINT NOT NULL, weekOfMonth SMALLINT DEFAULT NULL, time TIME(0) WITHOUT TIME ZONE DEFAULT NULL, location VARCHAR(255) DEFAULT NULL, latitude DOUBLE PRECISION DEFAULT NULL, longitude DOUBLE PRECISION DEFAULT NULL, createdAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updatedAt TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, disabledAt TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, validFrom DATE DEFAULT NULL, validUntil DATE DEFAULT NULL, rideCalculatorFqcn VARCHAR(255) DEFAULT NULL, description VARCHAR(255) DEFAULT NULL, specialDayOfWeek VARCHAR(255) DEFAULT NULL, specialWeekOfMonth VARCHAR(255) DEFAULT NULL, city_id INT DEFAULT NULL, user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F30C76C48BAC62AF ON city_cycle (city_id)');
        $this->addSql('CREATE INDEX IDX_F30C76C4A76ED395 ON city_cycle (user_id)');
        $this->addSql('CREATE TABLE app_user (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, roles JSONB DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, username VARCHAR(255) DEFAULT NULL, colorRed SMALLINT DEFAULT NULL, colorGreen SMALLINT DEFAULT NULL, colorBlue SMALLINT DEFAULT NULL, blurGalleries BOOLEAN DEFAULT false, enabled BOOLEAN DEFAULT false, updatedAt TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, createdAt TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, last_login TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, facebook_id VARCHAR(255) DEFAULT NULL, facebook_access_token TEXT DEFAULT NULL, strava_id VARCHAR(255) DEFAULT NULL, strava_access_token TEXT DEFAULT NULL, imageName VARCHAR(255) DEFAULT NULL, imageSize INT DEFAULT NULL, imageMimeType VARCHAR(255) DEFAULT NULL, ownProfilePhoto BOOLEAN DEFAULT false NOT NULL, forum_notifications BOOLEAN DEFAULT true NOT NULL, forum_post_count INT DEFAULT 0 NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE forum_subscription (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, global_scope BOOLEAN DEFAULT false NOT NULL, createdAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, thread_id INT DEFAULT NULL, board_id INT DEFAULT NULL, city_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9B189294E2904019 ON forum_subscription (thread_id)');
        $this->addSql('CREATE INDEX IDX_9B189294E7EC5785 ON forum_subscription (board_id)');
        $this->addSql('CREATE INDEX IDX_9B1892948BAC62AF ON forum_subscription (city_id)');
        $this->addSql('CREATE INDEX forum_subscription_user_index ON forum_subscription (user_id)');
        $this->addSql('CREATE TABLE photo (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, latitude DOUBLE PRECISION DEFAULT NULL, longitude DOUBLE PRECISION DEFAULT NULL, description TEXT DEFAULT NULL, enabled BOOLEAN NOT NULL, deleted BOOLEAN NOT NULL, creationDateTime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, imageName VARCHAR(255) NOT NULL, imageSize INT DEFAULT NULL, imageMimeType VARCHAR(255) DEFAULT NULL, backupName VARCHAR(255) DEFAULT NULL, backupSize INT DEFAULT NULL, backupMimeType VARCHAR(255) DEFAULT NULL, updatedAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, location VARCHAR(255) DEFAULT NULL, exifExposure VARCHAR(255) DEFAULT NULL, exifAperture VARCHAR(255) DEFAULT NULL, exifIso SMALLINT DEFAULT NULL, exifFocalLength DOUBLE PRECISION DEFAULT NULL, exifCamera VARCHAR(255) DEFAULT NULL, exifCreationDate TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT DEFAULT NULL, ride_id INT DEFAULT NULL, city_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_14B78418A76ED395 ON photo (user_id)');
        $this->addSql('CREATE INDEX IDX_14B78418302A8A70 ON photo (ride_id)');
        $this->addSql('CREATE INDEX IDX_14B784188BAC62AF ON photo (city_id)');
        $this->addSql('CREATE INDEX photo_exif_creation_date_index ON photo (exifCreationDate)');
        $this->addSql('CREATE TABLE participation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, dateTime TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, goingYes BOOLEAN DEFAULT NULL, goingMaybe BOOLEAN DEFAULT NULL, goingNo BOOLEAN DEFAULT NULL, ride_id INT DEFAULT NULL, user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AB55E24F302A8A70 ON participation (ride_id)');
        $this->addSql('CREATE INDEX IDX_AB55E24FA76ED395 ON participation (user_id)');
        $this->addSql('CREATE TABLE promotion (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(255) NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, createdAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updatedAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, query VARCHAR(255) NOT NULL, showMap BOOLEAN NOT NULL, mapCenterLatitude DOUBLE PRECISION DEFAULT NULL, mapCenterLongitude DOUBLE PRECISION DEFAULT NULL, mapZoomLevel INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE track_candidate (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, source VARCHAR(255) DEFAULT \'CANDIDATE_SOURCE_STRAVA\' NOT NULL, activityId BIGINT DEFAULT NULL, fileHash VARCHAR(40) DEFAULT NULL, trackFilename VARCHAR(255) DEFAULT NULL, originalName VARCHAR(255) DEFAULT NULL, name VARCHAR(255) NOT NULL, distance DOUBLE PRECISION NOT NULL, elapsedTime INT NOT NULL, type VARCHAR(255) NOT NULL, startDateTime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, startLatitude DOUBLE PRECISION NOT NULL, startLongitude DOUBLE PRECISION NOT NULL, endLatitude DOUBLE PRECISION NOT NULL, endLongitude DOUBLE PRECISION NOT NULL, polyline TEXT NOT NULL, createdAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, rejected BOOLEAN NOT NULL, user_id INT NOT NULL, ride_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C90A20B0A76ED395 ON track_candidate (user_id)');
        $this->addSql('CREATE INDEX IDX_C90A20B0302A8A70 ON track_candidate (ride_id)');
        $this->addSql('CREATE TABLE photo_candidate (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, fileHash VARCHAR(40) NOT NULL, stagedFilename VARCHAR(255) NOT NULL, originalName VARCHAR(255) DEFAULT NULL, mimeType VARCHAR(255) DEFAULT NULL, exifCreationDate TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, latitude DOUBLE PRECISION DEFAULT NULL, longitude DOUBLE PRECISION DEFAULT NULL, createdAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, rejected BOOLEAN DEFAULT false NOT NULL, user_id INT NOT NULL, ride_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C54CD865A76ED395 ON photo_candidate (user_id)');
        $this->addSql('CREATE INDEX IDX_C54CD865302A8A70 ON photo_candidate (ride_id)');
        $this->addSql('CREATE TABLE cityslug (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(50) DEFAULT NULL, city_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F8C0F8108BAC62AF ON cityslug (city_id)');
        $this->addSql('CREATE TABLE city_activity (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, score DOUBLE PRECISION NOT NULL, participationScore DOUBLE PRECISION NOT NULL, participationRawCount INT NOT NULL, photoScore DOUBLE PRECISION NOT NULL, photoRawCount INT NOT NULL, trackScore DOUBLE PRECISION NOT NULL, trackRawCount INT NOT NULL, socialFeedScore DOUBLE PRECISION NOT NULL, socialFeedRawCount INT NOT NULL, createdAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, city_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_29AC713C8BAC62AF ON city_activity (city_id)');
        $this->addSql('CREATE INDEX city_activity_city_created_at_idx ON city_activity (city_id, createdAt)');
        $this->addSql('CREATE TABLE alert (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, message TEXT NOT NULL, fromDateTime TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, untilDateTime TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, type VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE frontpage_teaser_button (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, caption VARCHAR(255) DEFAULT NULL, icon VARCHAR(32) DEFAULT NULL, link VARCHAR(255) DEFAULT NULL, class VARCHAR(255) DEFAULT NULL, position SMALLINT DEFAULT NULL, createdAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updatedAt TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, teaser_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CCA0C4A17ADE9C9E ON frontpage_teaser_button (teaser_id)');
        $this->addSql('CREATE TABLE weather (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, json TEXT DEFAULT NULL, weatherDateTime TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, creationDateTime TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, temperatureMin DOUBLE PRECISION DEFAULT NULL, temperatureMax DOUBLE PRECISION DEFAULT NULL, temperatureMorning DOUBLE PRECISION DEFAULT NULL, temperatureDay DOUBLE PRECISION DEFAULT NULL, temperatureEvening DOUBLE PRECISION DEFAULT NULL, temperatureNight DOUBLE PRECISION DEFAULT NULL, pressure DOUBLE PRECISION DEFAULT NULL, humidity DOUBLE PRECISION DEFAULT NULL, weatherCode INT DEFAULT NULL, weather VARCHAR(255) DEFAULT NULL, weatherDescription VARCHAR(255) DEFAULT NULL, weatherIcon VARCHAR(5) DEFAULT NULL, windSpeed DOUBLE PRECISION DEFAULT NULL, windDirection DOUBLE PRECISION DEFAULT NULL, clouds DOUBLE PRECISION DEFAULT NULL, precipitation DOUBLE PRECISION DEFAULT NULL, ride_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4CD0D36E302A8A70 ON weather (ride_id)');
        $this->addSql('CREATE TABLE frontpage_teaser (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, headline TEXT DEFAULT NULL, text TEXT DEFAULT NULL, imageName VARCHAR(255) DEFAULT NULL, imageSize INT DEFAULT NULL, imageMimeType VARCHAR(255) DEFAULT NULL, position SMALLINT DEFAULT NULL, createdAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updatedAt TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, validFrom TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, validUntil TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT DEFAULT NULL, city_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_26FF0B97A76ED395 ON frontpage_teaser (user_id)');
        $this->addSql('CREATE INDEX IDX_26FF0B978BAC62AF ON frontpage_teaser (city_id)');
        $this->addSql('CREATE TABLE city_blocked (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, blockStart TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, blockEnd TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, description TEXT DEFAULT NULL, photosLink BOOLEAN DEFAULT NULL, rideListLink BOOLEAN DEFAULT NULL, city_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_671D55D28BAC62AF ON city_blocked (city_id)');
        $this->addSql('CREATE TABLE track_polyline (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, resolution SMALLINT NOT NULL, polyline TEXT NOT NULL, numPoints INT NOT NULL, createdAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, track_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_ACF7A6C15ED23C43 ON track_polyline (track_id)');
        $this->addSql('CREATE UNIQUE INDEX track_resolution_unique ON track_polyline (track_id, resolution)');
        $this->addSql('CREATE TABLE oauth2_authorization_code (identifier CHAR(80) NOT NULL, expiry TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, userIdentifier VARCHAR(128) DEFAULT NULL, scopes TEXT DEFAULT NULL, revoked BOOLEAN NOT NULL, client VARCHAR(32) NOT NULL, PRIMARY KEY (identifier))');
        $this->addSql('CREATE INDEX IDX_509FEF5FC7440455 ON oauth2_authorization_code (client)');
        $this->addSql('CREATE TABLE oauth2_refresh_token (identifier CHAR(80) NOT NULL, expiry TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, revoked BOOLEAN NOT NULL, access_token CHAR(80) DEFAULT NULL, PRIMARY KEY (identifier))');
        $this->addSql('CREATE INDEX IDX_4DD90732B6A2DD68 ON oauth2_refresh_token (access_token)');
        $this->addSql('CREATE TABLE oauth2_client (name VARCHAR(128) NOT NULL, secret VARCHAR(128) DEFAULT NULL, redirectUris TEXT DEFAULT NULL, grants TEXT DEFAULT NULL, scopes TEXT DEFAULT NULL, active BOOLEAN NOT NULL, allowPlainTextPkce BOOLEAN DEFAULT false NOT NULL, identifier VARCHAR(32) NOT NULL, PRIMARY KEY (identifier))');
        $this->addSql('CREATE TABLE oauth2_access_token (identifier CHAR(80) NOT NULL, expiry TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, userIdentifier VARCHAR(128) DEFAULT NULL, scopes TEXT DEFAULT NULL, revoked BOOLEAN NOT NULL, client VARCHAR(32) NOT NULL, PRIMARY KEY (identifier))');
        $this->addSql('CREATE INDEX IDX_454D9673C7440455 ON oauth2_access_token (client)');
        $this->addSql('ALTER TABLE city ADD CONSTRAINT FK_2D5B0234A76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE city ADD CONSTRAINT FK_2D5B023498260155 FOREIGN KEY (region_id) REFERENCES region (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE city ADD CONSTRAINT FK_2D5B0234C552CF27 FOREIGN KEY (main_slug_id) REFERENCES cityslug (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE city ADD CONSTRAINT FK_2D5B0234B43140E7 FOREIGN KEY (lastthread_id) REFERENCES thread (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE region ADD CONSTRAINT FK_F62F176727ACA70 FOREIGN KEY (parent_id) REFERENCES region (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ride ADD CONSTRAINT FK_9B3D7CD0A76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ride ADD CONSTRAINT FK_9B3D7CD05EC1162 FOREIGN KEY (cycle_id) REFERENCES city_cycle (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ride ADD CONSTRAINT FK_9B3D7CD08BAC62AF FOREIGN KEY (city_id) REFERENCES city (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ride ADD CONSTRAINT FK_9B3D7CD04DFE7F82 FOREIGN KEY (featured_photo) REFERENCES photo (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ride_estimate ADD CONSTRAINT FK_ADC7E493A76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ride_estimate ADD CONSTRAINT FK_ADC7E493302A8A70 FOREIGN KEY (ride_id) REFERENCES ride (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ride_estimate ADD CONSTRAINT FK_ADC7E4935ED23C43 FOREIGN KEY (track_id) REFERENCES track (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE location ADD CONSTRAINT FK_5E9E89CB8BAC62AF FOREIGN KEY (city_id) REFERENCES city (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE post ADD CONSTRAINT FK_5A8A6C8D727ACA70 FOREIGN KEY (parent_id) REFERENCES post (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE post ADD CONSTRAINT FK_5A8A6C8DA76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE post ADD CONSTRAINT FK_5A8A6C8D302A8A70 FOREIGN KEY (ride_id) REFERENCES ride (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE post ADD CONSTRAINT FK_5A8A6C8D8BAC62AF FOREIGN KEY (city_id) REFERENCES city (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE post ADD CONSTRAINT FK_5A8A6C8DE2904019 FOREIGN KEY (thread_id) REFERENCES thread (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE post ADD CONSTRAINT FK_5A8A6C8D7E9E4C8C FOREIGN KEY (photo_id) REFERENCES photo (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE post ADD CONSTRAINT FK_5A8A6C8D2793CC5E FOREIGN KEY (updated_by_user_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE social_network_profile ADD CONSTRAINT FK_3AC92AE6A76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE social_network_profile ADD CONSTRAINT FK_3AC92AE68BAC62AF FOREIGN KEY (city_id) REFERENCES city (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE social_network_profile ADD CONSTRAINT FK_3AC92AE6302A8A70 FOREIGN KEY (ride_id) REFERENCES ride (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE social_network_profile ADD CONSTRAINT FK_3AC92AE67B4822BF FOREIGN KEY (subride_id) REFERENCES subride (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE social_network_profile ADD CONSTRAINT FK_3AC92AE63174800F FOREIGN KEY (createdBy_id) REFERENCES app_user (id)');
        $this->addSql('ALTER TABLE subride ADD CONSTRAINT FK_42880E5B302A8A70 FOREIGN KEY (ride_id) REFERENCES ride (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE subride ADD CONSTRAINT FK_42880E5BA76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE track ADD CONSTRAINT FK_D6E3F8A6302A8A70 FOREIGN KEY (ride_id) REFERENCES ride (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE track ADD CONSTRAINT FK_D6E3F8A6A76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE board ADD CONSTRAINT FK_58562B47B43140E7 FOREIGN KEY (lastthread_id) REFERENCES thread (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE thread ADD CONSTRAINT FK_31204C83E7EC5785 FOREIGN KEY (board_id) REFERENCES board (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE thread ADD CONSTRAINT FK_31204C838BAC62AF FOREIGN KEY (city_id) REFERENCES city (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE thread ADD CONSTRAINT FK_31204C83524E4EB7 FOREIGN KEY (firstpost_id) REFERENCES post (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE thread ADD CONSTRAINT FK_31204C8338BD6675 FOREIGN KEY (lastpost_id) REFERENCES post (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE city_cycle ADD CONSTRAINT FK_F30C76C48BAC62AF FOREIGN KEY (city_id) REFERENCES city (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE city_cycle ADD CONSTRAINT FK_F30C76C4A76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE forum_subscription ADD CONSTRAINT FK_9B189294A76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE forum_subscription ADD CONSTRAINT FK_9B189294E2904019 FOREIGN KEY (thread_id) REFERENCES thread (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE forum_subscription ADD CONSTRAINT FK_9B189294E7EC5785 FOREIGN KEY (board_id) REFERENCES board (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE forum_subscription ADD CONSTRAINT FK_9B1892948BAC62AF FOREIGN KEY (city_id) REFERENCES city (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE photo ADD CONSTRAINT FK_14B78418A76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE photo ADD CONSTRAINT FK_14B78418302A8A70 FOREIGN KEY (ride_id) REFERENCES ride (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE photo ADD CONSTRAINT FK_14B784188BAC62AF FOREIGN KEY (city_id) REFERENCES city (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE participation ADD CONSTRAINT FK_AB55E24F302A8A70 FOREIGN KEY (ride_id) REFERENCES ride (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE participation ADD CONSTRAINT FK_AB55E24FA76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE track_candidate ADD CONSTRAINT FK_C90A20B0A76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE track_candidate ADD CONSTRAINT FK_C90A20B0302A8A70 FOREIGN KEY (ride_id) REFERENCES ride (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE photo_candidate ADD CONSTRAINT FK_C54CD865A76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE photo_candidate ADD CONSTRAINT FK_C54CD865302A8A70 FOREIGN KEY (ride_id) REFERENCES ride (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cityslug ADD CONSTRAINT FK_F8C0F8108BAC62AF FOREIGN KEY (city_id) REFERENCES city (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE city_activity ADD CONSTRAINT FK_29AC713C8BAC62AF FOREIGN KEY (city_id) REFERENCES city (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE frontpage_teaser_button ADD CONSTRAINT FK_CCA0C4A17ADE9C9E FOREIGN KEY (teaser_id) REFERENCES frontpage_teaser (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE weather ADD CONSTRAINT FK_4CD0D36E302A8A70 FOREIGN KEY (ride_id) REFERENCES ride (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE frontpage_teaser ADD CONSTRAINT FK_26FF0B97A76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE frontpage_teaser ADD CONSTRAINT FK_26FF0B978BAC62AF FOREIGN KEY (city_id) REFERENCES city (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE city_blocked ADD CONSTRAINT FK_671D55D28BAC62AF FOREIGN KEY (city_id) REFERENCES city (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE track_polyline ADD CONSTRAINT FK_ACF7A6C15ED23C43 FOREIGN KEY (track_id) REFERENCES track (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE oauth2_authorization_code ADD CONSTRAINT FK_509FEF5FC7440455 FOREIGN KEY (client) REFERENCES oauth2_client (identifier) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE oauth2_refresh_token ADD CONSTRAINT FK_4DD90732B6A2DD68 FOREIGN KEY (access_token) REFERENCES oauth2_access_token (identifier) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE oauth2_access_token ADD CONSTRAINT FK_454D9673C7440455 FOREIGN KEY (client) REFERENCES oauth2_client (identifier) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // Vor der Baseline liegt nichts, worauf sich zurueckrollen liesse: ein
        // funktionierendes down() hiesse hier, die gesamte Datenbank zu
        // loeschen. Wer das wirklich will, nimmt doctrine:schema:drop.
        throw new \LogicException('Die Baseline laesst sich nicht zurueckrollen.');
    }
}
