<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Ausgangspunkt der Migrationsgeschichte.
 *
 * Die 119 Migrationen davor waren MySQL-only; 97 von ihnen riefen
 * $this->connection->getDatabasePlatform()->getName() auf, eine Methode, die es
 * seit DBAL 4 nicht mehr gibt. Die Kette liess sich damit ohnehin nicht mehr von
 * null abspielen. Sie bleibt in der Git-Historie erhalten; hier steht
 * stattdessen das Schema, das das Entity-Modell heute beschreibt.
 *
 * Auf einer bestehenden Datenbank wird diese Migration nicht ausgefuehrt,
 * sondern als erledigt eingetragen:
 *
 *   bin/console doctrine:migrations:version --add \
 *       'DoctrineMigrations\Version20260904120000' --no-interaction
 */
final class Version20260904120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Baseline: legt das vollstaendige Schema mit 31 Tabellen an';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE cityslug (id INT AUTO_INCREMENT NOT NULL, slug VARCHAR(50) DEFAULT NULL, city_id INT DEFAULT NULL, INDEX IDX_F8C0F8108BAC62AF (city_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE region (id INT AUTO_INCREMENT NOT NULL, slug VARCHAR(255) DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, description LONGTEXT DEFAULT NULL, wikidataEntityId VARCHAR(255) DEFAULT NULL, parent_id INT DEFAULT NULL, INDEX IDX_F62F176727ACA70 (parent_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE city_cycle (id INT AUTO_INCREMENT NOT NULL, dayOfWeek SMALLINT NOT NULL, weekOfMonth SMALLINT DEFAULT NULL, time TIME DEFAULT NULL, location VARCHAR(255) DEFAULT NULL, latitude DOUBLE PRECISION DEFAULT NULL, longitude DOUBLE PRECISION DEFAULT NULL, createdAt DATETIME NOT NULL, updatedAt DATETIME DEFAULT NULL, disabledAt DATETIME DEFAULT NULL, validFrom DATE DEFAULT NULL, validUntil DATE DEFAULT NULL, rideCalculatorFqcn VARCHAR(255) DEFAULT NULL, description VARCHAR(255) DEFAULT NULL, specialDayOfWeek VARCHAR(255) DEFAULT NULL, specialWeekOfMonth VARCHAR(255) DEFAULT NULL, city_id INT DEFAULT NULL, user_id INT DEFAULT NULL, INDEX IDX_F30C76C48BAC62AF (city_id), INDEX IDX_F30C76C4A76ED395 (user_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE post (id INT AUTO_INCREMENT NOT NULL, latitude DOUBLE PRECISION DEFAULT NULL, longitude DOUBLE PRECISION DEFAULT NULL, dateTime DATETIME DEFAULT NULL, message LONGTEXT DEFAULT NULL, updatedAt DATETIME DEFAULT NULL, enabled TINYINT DEFAULT NULL, parent_id INT DEFAULT NULL, user_id INT DEFAULT NULL, ride_id INT DEFAULT NULL, city_id INT DEFAULT NULL, thread_id INT DEFAULT NULL, photo_id INT DEFAULT NULL, updated_by_user_id INT DEFAULT NULL, INDEX IDX_5A8A6C8D727ACA70 (parent_id), INDEX IDX_5A8A6C8DA76ED395 (user_id), INDEX IDX_5A8A6C8D302A8A70 (ride_id), INDEX IDX_5A8A6C8D8BAC62AF (city_id), INDEX IDX_5A8A6C8DE2904019 (thread_id), INDEX IDX_5A8A6C8D7E9E4C8C (photo_id), INDEX IDX_5A8A6C8D2793CC5E (updated_by_user_id), INDEX post_date_time_index (dateTime), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE subride (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) DEFAULT NULL, description LONGTEXT DEFAULT NULL, dateTime DATETIME DEFAULT NULL, createdAt DATETIME NOT NULL, updatedAt DATETIME DEFAULT NULL, location VARCHAR(255) DEFAULT NULL, latitude DOUBLE PRECISION DEFAULT NULL, longitude DOUBLE PRECISION DEFAULT NULL, ride_id INT DEFAULT NULL, user_id INT DEFAULT NULL, INDEX IDX_42880E5B302A8A70 (ride_id), INDEX IDX_42880E5BA76ED395 (user_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE city (id INT AUTO_INCREMENT NOT NULL, city VARCHAR(50) DEFAULT NULL, title VARCHAR(100) DEFAULT NULL, description LONGTEXT DEFAULT NULL, latitude DOUBLE PRECISION DEFAULT NULL, longitude DOUBLE PRECISION DEFAULT NULL, enabled TINYINT DEFAULT NULL, cityPopulation INT DEFAULT NULL, punchLine VARCHAR(255) DEFAULT NULL, longDescription LONGTEXT DEFAULT NULL, imageName VARCHAR(255) DEFAULT NULL, imageSize INT DEFAULT NULL, imageMimeType VARCHAR(255) DEFAULT NULL, updatedAt DATETIME DEFAULT NULL, createdAt DATETIME DEFAULT NULL, enableBoard TINYINT DEFAULT NULL, timezone VARCHAR(255) DEFAULT NULL, threadNumber INT DEFAULT NULL, postNumber INT DEFAULT NULL, colorRed INT DEFAULT NULL, colorGreen INT DEFAULT NULL, colorBlue INT DEFAULT NULL, rideNamer VARCHAR(255) DEFAULT NULL, wikidataEntityId VARCHAR(255) DEFAULT NULL, activityScore DOUBLE PRECISION DEFAULT NULL, user_id INT DEFAULT NULL, region_id INT DEFAULT NULL, main_slug_id INT DEFAULT NULL, lastthread_id INT DEFAULT NULL, INDEX IDX_2D5B0234A76ED395 (user_id), INDEX IDX_2D5B023498260155 (region_id), INDEX IDX_2D5B0234C552CF27 (main_slug_id), INDEX IDX_2D5B0234B43140E7 (lastthread_id), INDEX city_created_at_index (createdAt), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE city_activity (id INT AUTO_INCREMENT NOT NULL, score DOUBLE PRECISION NOT NULL, participationScore DOUBLE PRECISION NOT NULL, participationRawCount INT NOT NULL, photoScore DOUBLE PRECISION NOT NULL, photoRawCount INT NOT NULL, trackScore DOUBLE PRECISION NOT NULL, trackRawCount INT NOT NULL, socialFeedScore DOUBLE PRECISION NOT NULL, socialFeedRawCount INT NOT NULL, createdAt DATETIME NOT NULL, city_id INT NOT NULL, INDEX IDX_29AC713C8BAC62AF (city_id), INDEX city_activity_city_created_at_idx (city_id, createdAt), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE promotion (id INT AUTO_INCREMENT NOT NULL, slug VARCHAR(255) NOT NULL, title VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, createdAt DATETIME NOT NULL, updatedAt DATETIME NOT NULL, query VARCHAR(255) NOT NULL, showMap TINYINT NOT NULL, mapCenterLatitude DOUBLE PRECISION DEFAULT NULL, mapCenterLongitude DOUBLE PRECISION DEFAULT NULL, mapZoomLevel INT DEFAULT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE alert (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, message LONGTEXT NOT NULL, fromDateTime DATETIME DEFAULT NULL, untilDateTime DATETIME DEFAULT NULL, type VARCHAR(255) NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE user (id INT AUTO_INCREMENT NOT NULL, roles JSON DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, username VARCHAR(255) DEFAULT NULL, colorRed SMALLINT DEFAULT NULL, colorGreen SMALLINT DEFAULT NULL, colorBlue SMALLINT DEFAULT NULL, blurGalleries TINYINT DEFAULT 0, enabled TINYINT DEFAULT 0, updatedAt DATETIME DEFAULT NULL, createdAt DATETIME DEFAULT NULL, last_login DATETIME DEFAULT NULL, facebook_id VARCHAR(255) DEFAULT NULL, facebook_access_token LONGTEXT DEFAULT NULL, strava_id VARCHAR(255) DEFAULT NULL, strava_access_token LONGTEXT DEFAULT NULL, imageName VARCHAR(255) DEFAULT NULL, imageSize INT DEFAULT NULL, imageMimeType VARCHAR(255) DEFAULT NULL, ownProfilePhoto TINYINT DEFAULT 0 NOT NULL, forum_notifications TINYINT DEFAULT 1 NOT NULL, forum_post_count INT DEFAULT 0 NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE track (id INT AUTO_INCREMENT NOT NULL, username VARCHAR(255) DEFAULT NULL, creationDateTime DATETIME DEFAULT NULL, startDateTime DATETIME DEFAULT NULL, endDateTime DATETIME DEFAULT NULL, distance DOUBLE PRECISION DEFAULT NULL, points INT DEFAULT NULL, startPoint INT DEFAULT NULL, endPoint INT DEFAULT NULL, enabled TINYINT DEFAULT NULL, deleted TINYINT DEFAULT NULL, latLngList LONGTEXT DEFAULT NULL, trackFilename VARCHAR(255) DEFAULT NULL, trackSize INT DEFAULT NULL, trackMimeType VARCHAR(255) DEFAULT NULL, updatedAt DATETIME DEFAULT NULL, source VARCHAR(255) DEFAULT NULL, stravaActitityId BIGINT DEFAULT NULL, reviewed TINYINT NOT NULL, app VARCHAR(255) DEFAULT NULL, ride_id INT DEFAULT NULL, user_id INT DEFAULT NULL, INDEX IDX_D6E3F8A6302A8A70 (ride_id), INDEX IDX_D6E3F8A6A76ED395 (user_id), INDEX track_creation_date_time_index (creationDateTime), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE frontpage_teaser_button (id INT AUTO_INCREMENT NOT NULL, caption VARCHAR(255) DEFAULT NULL, icon VARCHAR(32) DEFAULT NULL, link VARCHAR(255) DEFAULT NULL, class VARCHAR(255) DEFAULT NULL, position SMALLINT DEFAULT NULL, createdAt DATETIME NOT NULL, updatedAt DATETIME DEFAULT NULL, teaser_id INT DEFAULT NULL, INDEX IDX_CCA0C4A17ADE9C9E (teaser_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE weather (id INT AUTO_INCREMENT NOT NULL, json LONGTEXT DEFAULT NULL, weatherDateTime DATETIME DEFAULT NULL, creationDateTime DATETIME DEFAULT NULL, temperatureMin DOUBLE PRECISION DEFAULT NULL, temperatureMax DOUBLE PRECISION DEFAULT NULL, temperatureMorning DOUBLE PRECISION DEFAULT NULL, temperatureDay DOUBLE PRECISION DEFAULT NULL, temperatureEvening DOUBLE PRECISION DEFAULT NULL, temperatureNight DOUBLE PRECISION DEFAULT NULL, pressure DOUBLE PRECISION DEFAULT NULL, humidity DOUBLE PRECISION DEFAULT NULL, weatherCode INT DEFAULT NULL, weather VARCHAR(255) DEFAULT NULL, weatherDescription VARCHAR(255) DEFAULT NULL, weatherIcon VARCHAR(5) DEFAULT NULL, windSpeed DOUBLE PRECISION DEFAULT NULL, windDirection DOUBLE PRECISION DEFAULT NULL, clouds DOUBLE PRECISION DEFAULT NULL, precipitation DOUBLE PRECISION DEFAULT NULL, ride_id INT DEFAULT NULL, INDEX IDX_4CD0D36E302A8A70 (ride_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE photo (id INT AUTO_INCREMENT NOT NULL, latitude DOUBLE PRECISION DEFAULT NULL, longitude DOUBLE PRECISION DEFAULT NULL, description LONGTEXT DEFAULT NULL, enabled TINYINT NOT NULL, deleted TINYINT NOT NULL, creationDateTime DATETIME NOT NULL, imageName VARCHAR(255) NOT NULL, imageSize INT DEFAULT NULL, imageMimeType VARCHAR(255) DEFAULT NULL, backupName VARCHAR(255) DEFAULT NULL, backupSize INT DEFAULT NULL, backupMimeType VARCHAR(255) DEFAULT NULL, updatedAt DATETIME NOT NULL, location VARCHAR(255) DEFAULT NULL, exifExposure VARCHAR(255) DEFAULT NULL, exifAperture VARCHAR(255) DEFAULT NULL, exifIso SMALLINT DEFAULT NULL, exifFocalLength DOUBLE PRECISION DEFAULT NULL, exifCamera VARCHAR(255) DEFAULT NULL, exifCreationDate DATETIME NOT NULL, user_id INT DEFAULT NULL, ride_id INT DEFAULT NULL, city_id INT DEFAULT NULL, INDEX IDX_14B78418A76ED395 (user_id), INDEX IDX_14B78418302A8A70 (ride_id), INDEX IDX_14B784188BAC62AF (city_id), INDEX photo_exif_creation_date_index (exifCreationDate), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE social_network_profile (id INT AUTO_INCREMENT NOT NULL, identifier VARCHAR(255) NOT NULL, network VARCHAR(255) NOT NULL, enabled TINYINT NOT NULL, createdAt DATETIME DEFAULT NULL, autoPublish TINYINT NOT NULL, lastFetchSuccessDateTime DATETIME DEFAULT NULL, lastFetchFailureDateTime DATETIME DEFAULT NULL, lastFetchFailureError LONGTEXT DEFAULT NULL, autoFetch TINYINT NOT NULL, additionalData LONGTEXT DEFAULT NULL, feedsProfileId INT DEFAULT NULL, user_id INT DEFAULT NULL, city_id INT DEFAULT NULL, ride_id INT DEFAULT NULL, subride_id INT DEFAULT NULL, createdBy_id INT DEFAULT NULL, INDEX IDX_3AC92AE6A76ED395 (user_id), INDEX IDX_3AC92AE68BAC62AF (city_id), INDEX IDX_3AC92AE6302A8A70 (ride_id), INDEX IDX_3AC92AE67B4822BF (subride_id), INDEX IDX_3AC92AE63174800F (createdBy_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE frontpage_teaser (id INT AUTO_INCREMENT NOT NULL, headline LONGTEXT DEFAULT NULL, text LONGTEXT DEFAULT NULL, imageName VARCHAR(255) DEFAULT NULL, imageSize INT DEFAULT NULL, imageMimeType VARCHAR(255) DEFAULT NULL, position SMALLINT DEFAULT NULL, createdAt DATETIME NOT NULL, updatedAt DATETIME DEFAULT NULL, validFrom DATETIME DEFAULT NULL, validUntil DATETIME DEFAULT NULL, user_id INT DEFAULT NULL, city_id INT DEFAULT NULL, INDEX IDX_26FF0B97A76ED395 (user_id), INDEX IDX_26FF0B978BAC62AF (city_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE participation (id INT AUTO_INCREMENT NOT NULL, dateTime DATETIME DEFAULT NULL, goingYes TINYINT DEFAULT NULL, goingMaybe TINYINT DEFAULT NULL, goingNo TINYINT DEFAULT NULL, ride_id INT DEFAULT NULL, user_id INT DEFAULT NULL, INDEX IDX_AB55E24F302A8A70 (ride_id), INDEX IDX_AB55E24FA76ED395 (user_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE forum_subscription (id INT AUTO_INCREMENT NOT NULL, global_scope TINYINT DEFAULT 0 NOT NULL, createdAt DATETIME NOT NULL, user_id INT NOT NULL, thread_id INT DEFAULT NULL, board_id INT DEFAULT NULL, city_id INT DEFAULT NULL, INDEX IDX_9B189294E2904019 (thread_id), INDEX IDX_9B189294E7EC5785 (board_id), INDEX IDX_9B1892948BAC62AF (city_id), INDEX forum_subscription_user_index (user_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE location (id INT AUTO_INCREMENT NOT NULL, slug VARCHAR(255) DEFAULT NULL, latitude DOUBLE PRECISION DEFAULT NULL, longitude DOUBLE PRECISION DEFAULT NULL, title VARCHAR(255) DEFAULT NULL, description LONGTEXT DEFAULT NULL, city_id INT DEFAULT NULL, INDEX IDX_5E9E89CB8BAC62AF (city_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE board (id INT AUTO_INCREMENT NOT NULL, title LONGTEXT DEFAULT NULL, description LONGTEXT DEFAULT NULL, threadNumber INT DEFAULT NULL, postNumber INT DEFAULT NULL, position INT DEFAULT NULL, enabled TINYINT DEFAULT NULL, slug VARCHAR(255) DEFAULT NULL, lastthread_id INT DEFAULT NULL, UNIQUE INDEX UNIQ_58562B47B43140E7 (lastthread_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE photo_candidate (id INT AUTO_INCREMENT NOT NULL, fileHash VARCHAR(40) NOT NULL, stagedFilename VARCHAR(255) NOT NULL, originalName VARCHAR(255) DEFAULT NULL, mimeType VARCHAR(255) DEFAULT NULL, exifCreationDate DATETIME DEFAULT NULL, latitude DOUBLE PRECISION DEFAULT NULL, longitude DOUBLE PRECISION DEFAULT NULL, createdAt DATETIME NOT NULL, rejected TINYINT DEFAULT 0 NOT NULL, user_id INT NOT NULL, ride_id INT DEFAULT NULL, INDEX IDX_C54CD865A76ED395 (user_id), INDEX IDX_C54CD865302A8A70 (ride_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE ride (id INT AUTO_INCREMENT NOT NULL, slug VARCHAR(255) DEFAULT NULL, title VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, socialDescription LONGTEXT DEFAULT NULL, dateTime DATETIME DEFAULT NULL, location VARCHAR(512) DEFAULT NULL, latitude DOUBLE PRECISION DEFAULT NULL, longitude DOUBLE PRECISION DEFAULT NULL, estimatedParticipants SMALLINT DEFAULT NULL, estimatedDistance DOUBLE PRECISION DEFAULT NULL, estimatedDuration DOUBLE PRECISION DEFAULT NULL, createdAt DATETIME DEFAULT NULL, updatedAt DATETIME DEFAULT NULL, participationsNumberYes INT DEFAULT NULL, participationsNumberMaybe INT DEFAULT NULL, participationsNumberNo INT DEFAULT NULL, restrictedPhotoAccess TINYINT DEFAULT NULL, imageName VARCHAR(255) DEFAULT NULL, imageSize INT DEFAULT NULL, imageMimeType VARCHAR(255) DEFAULT NULL, enabled TINYINT DEFAULT 1 NOT NULL, disabledReason VARCHAR(255) DEFAULT NULL, rideType VARCHAR(255) DEFAULT NULL, disabledReasonMessage LONGTEXT DEFAULT NULL, user_id INT DEFAULT NULL, cycle_id INT DEFAULT NULL, city_id INT DEFAULT NULL, featured_photo INT DEFAULT NULL, INDEX IDX_9B3D7CD0A76ED395 (user_id), INDEX IDX_9B3D7CD05EC1162 (cycle_id), INDEX IDX_9B3D7CD08BAC62AF (city_id), INDEX IDX_9B3D7CD04DFE7F82 (featured_photo), INDEX ride_date_time_index (dateTime), INDEX ride_created_at_index (createdAt), INDEX ride_updated_at_index (updatedAt), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE thread (id INT AUTO_INCREMENT NOT NULL, title LONGTEXT DEFAULT NULL, slug VARCHAR(255) DEFAULT NULL, postNumber INT DEFAULT NULL, enabled TINYINT DEFAULT NULL, locked TINYINT DEFAULT 0 NOT NULL, sticky TINYINT DEFAULT 0 NOT NULL, board_id INT DEFAULT NULL, city_id INT DEFAULT NULL, firstpost_id INT DEFAULT NULL, lastpost_id INT DEFAULT NULL, INDEX IDX_31204C83E7EC5785 (board_id), INDEX IDX_31204C838BAC62AF (city_id), UNIQUE INDEX UNIQ_31204C83524E4EB7 (firstpost_id), UNIQUE INDEX UNIQ_31204C8338BD6675 (lastpost_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE city_blocked (id INT AUTO_INCREMENT NOT NULL, blockStart DATETIME DEFAULT NULL, blockEnd DATETIME DEFAULT NULL, description LONGTEXT DEFAULT NULL, photosLink TINYINT DEFAULT NULL, rideListLink TINYINT DEFAULT NULL, city_id INT DEFAULT NULL, INDEX IDX_671D55D28BAC62AF (city_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE track_polyline (id INT AUTO_INCREMENT NOT NULL, resolution SMALLINT NOT NULL, polyline LONGTEXT NOT NULL, numPoints INT NOT NULL, createdAt DATETIME NOT NULL, track_id INT NOT NULL, INDEX IDX_ACF7A6C15ED23C43 (track_id), UNIQUE INDEX track_resolution_unique (track_id, resolution), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE track_candidate (id INT AUTO_INCREMENT NOT NULL, source VARCHAR(255) DEFAULT \'CANDIDATE_SOURCE_STRAVA\' NOT NULL, activityId BIGINT DEFAULT NULL, fileHash VARCHAR(40) DEFAULT NULL, trackFilename VARCHAR(255) DEFAULT NULL, originalName VARCHAR(255) DEFAULT NULL, name VARCHAR(255) NOT NULL, distance DOUBLE PRECISION NOT NULL, elapsedTime INT NOT NULL, type VARCHAR(255) NOT NULL, startDateTime DATETIME NOT NULL, startLatitude DOUBLE PRECISION NOT NULL, startLongitude DOUBLE PRECISION NOT NULL, endLatitude DOUBLE PRECISION NOT NULL, endLongitude DOUBLE PRECISION NOT NULL, polyline LONGTEXT NOT NULL, createdAt DATETIME NOT NULL, rejected TINYINT NOT NULL, user_id INT NOT NULL, ride_id INT DEFAULT NULL, INDEX IDX_C90A20B0A76ED395 (user_id), INDEX IDX_C90A20B0302A8A70 (ride_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE ride_estimate (id INT AUTO_INCREMENT NOT NULL, latitude DOUBLE PRECISION DEFAULT NULL, longitude DOUBLE PRECISION DEFAULT NULL, estimatedParticipants SMALLINT DEFAULT NULL, estimatedDistance DOUBLE PRECISION DEFAULT NULL, estimatedDuration DOUBLE PRECISION DEFAULT NULL, dateTime DATETIME DEFAULT NULL, createdAt DATETIME DEFAULT NULL, source VARCHAR(255) DEFAULT NULL, user_id INT DEFAULT NULL, ride_id INT DEFAULT NULL, track_id INT DEFAULT NULL, INDEX IDX_ADC7E493A76ED395 (user_id), INDEX IDX_ADC7E493302A8A70 (ride_id), UNIQUE INDEX UNIQ_ADC7E4935ED23C43 (track_id), INDEX ride_estimate_date_time_index (dateTime), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE oauth2_authorization_code (identifier CHAR(80) NOT NULL, expiry DATETIME NOT NULL, userIdentifier VARCHAR(128) DEFAULT NULL, scopes TEXT DEFAULT NULL, revoked TINYINT NOT NULL, client VARCHAR(32) NOT NULL, INDEX IDX_509FEF5FC7440455 (client), PRIMARY KEY (identifier)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE oauth2_refresh_token (identifier CHAR(80) NOT NULL, expiry DATETIME NOT NULL, revoked TINYINT NOT NULL, access_token CHAR(80) DEFAULT NULL, INDEX IDX_4DD90732B6A2DD68 (access_token), PRIMARY KEY (identifier)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE oauth2_client (name VARCHAR(128) NOT NULL, secret VARCHAR(128) DEFAULT NULL, redirectUris TEXT DEFAULT NULL, grants TEXT DEFAULT NULL, scopes TEXT DEFAULT NULL, active TINYINT NOT NULL, allowPlainTextPkce TINYINT DEFAULT 0 NOT NULL, identifier VARCHAR(32) NOT NULL, PRIMARY KEY (identifier)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE oauth2_access_token (identifier CHAR(80) NOT NULL, expiry DATETIME NOT NULL, userIdentifier VARCHAR(128) DEFAULT NULL, scopes TEXT DEFAULT NULL, revoked TINYINT NOT NULL, client VARCHAR(32) NOT NULL, INDEX IDX_454D9673C7440455 (client), PRIMARY KEY (identifier)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('ALTER TABLE cityslug ADD CONSTRAINT FK_F8C0F8108BAC62AF FOREIGN KEY (city_id) REFERENCES city (id)');
        $this->addSql('ALTER TABLE region ADD CONSTRAINT FK_F62F176727ACA70 FOREIGN KEY (parent_id) REFERENCES region (id)');
        $this->addSql('ALTER TABLE city_cycle ADD CONSTRAINT FK_F30C76C48BAC62AF FOREIGN KEY (city_id) REFERENCES city (id)');
        $this->addSql('ALTER TABLE city_cycle ADD CONSTRAINT FK_F30C76C4A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE post ADD CONSTRAINT FK_5A8A6C8D727ACA70 FOREIGN KEY (parent_id) REFERENCES post (id)');
        $this->addSql('ALTER TABLE post ADD CONSTRAINT FK_5A8A6C8DA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE post ADD CONSTRAINT FK_5A8A6C8D302A8A70 FOREIGN KEY (ride_id) REFERENCES ride (id)');
        $this->addSql('ALTER TABLE post ADD CONSTRAINT FK_5A8A6C8D8BAC62AF FOREIGN KEY (city_id) REFERENCES city (id)');
        $this->addSql('ALTER TABLE post ADD CONSTRAINT FK_5A8A6C8DE2904019 FOREIGN KEY (thread_id) REFERENCES thread (id)');
        $this->addSql('ALTER TABLE post ADD CONSTRAINT FK_5A8A6C8D7E9E4C8C FOREIGN KEY (photo_id) REFERENCES photo (id)');
        $this->addSql('ALTER TABLE post ADD CONSTRAINT FK_5A8A6C8D2793CC5E FOREIGN KEY (updated_by_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE subride ADD CONSTRAINT FK_42880E5B302A8A70 FOREIGN KEY (ride_id) REFERENCES ride (id)');
        $this->addSql('ALTER TABLE subride ADD CONSTRAINT FK_42880E5BA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE city ADD CONSTRAINT FK_2D5B0234A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE city ADD CONSTRAINT FK_2D5B023498260155 FOREIGN KEY (region_id) REFERENCES region (id)');
        $this->addSql('ALTER TABLE city ADD CONSTRAINT FK_2D5B0234C552CF27 FOREIGN KEY (main_slug_id) REFERENCES cityslug (id)');
        $this->addSql('ALTER TABLE city ADD CONSTRAINT FK_2D5B0234B43140E7 FOREIGN KEY (lastthread_id) REFERENCES thread (id)');
        $this->addSql('ALTER TABLE city_activity ADD CONSTRAINT FK_29AC713C8BAC62AF FOREIGN KEY (city_id) REFERENCES city (id)');
        $this->addSql('ALTER TABLE track ADD CONSTRAINT FK_D6E3F8A6302A8A70 FOREIGN KEY (ride_id) REFERENCES ride (id)');
        $this->addSql('ALTER TABLE track ADD CONSTRAINT FK_D6E3F8A6A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE frontpage_teaser_button ADD CONSTRAINT FK_CCA0C4A17ADE9C9E FOREIGN KEY (teaser_id) REFERENCES frontpage_teaser (id)');
        $this->addSql('ALTER TABLE weather ADD CONSTRAINT FK_4CD0D36E302A8A70 FOREIGN KEY (ride_id) REFERENCES ride (id)');
        $this->addSql('ALTER TABLE photo ADD CONSTRAINT FK_14B78418A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE photo ADD CONSTRAINT FK_14B78418302A8A70 FOREIGN KEY (ride_id) REFERENCES ride (id)');
        $this->addSql('ALTER TABLE photo ADD CONSTRAINT FK_14B784188BAC62AF FOREIGN KEY (city_id) REFERENCES city (id)');
        $this->addSql('ALTER TABLE social_network_profile ADD CONSTRAINT FK_3AC92AE6A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE social_network_profile ADD CONSTRAINT FK_3AC92AE68BAC62AF FOREIGN KEY (city_id) REFERENCES city (id)');
        $this->addSql('ALTER TABLE social_network_profile ADD CONSTRAINT FK_3AC92AE6302A8A70 FOREIGN KEY (ride_id) REFERENCES ride (id)');
        $this->addSql('ALTER TABLE social_network_profile ADD CONSTRAINT FK_3AC92AE67B4822BF FOREIGN KEY (subride_id) REFERENCES subride (id)');
        $this->addSql('ALTER TABLE social_network_profile ADD CONSTRAINT FK_3AC92AE63174800F FOREIGN KEY (createdBy_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE frontpage_teaser ADD CONSTRAINT FK_26FF0B97A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE frontpage_teaser ADD CONSTRAINT FK_26FF0B978BAC62AF FOREIGN KEY (city_id) REFERENCES city (id)');
        $this->addSql('ALTER TABLE participation ADD CONSTRAINT FK_AB55E24F302A8A70 FOREIGN KEY (ride_id) REFERENCES ride (id)');
        $this->addSql('ALTER TABLE participation ADD CONSTRAINT FK_AB55E24FA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE forum_subscription ADD CONSTRAINT FK_9B189294A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE forum_subscription ADD CONSTRAINT FK_9B189294E2904019 FOREIGN KEY (thread_id) REFERENCES thread (id)');
        $this->addSql('ALTER TABLE forum_subscription ADD CONSTRAINT FK_9B189294E7EC5785 FOREIGN KEY (board_id) REFERENCES board (id)');
        $this->addSql('ALTER TABLE forum_subscription ADD CONSTRAINT FK_9B1892948BAC62AF FOREIGN KEY (city_id) REFERENCES city (id)');
        $this->addSql('ALTER TABLE location ADD CONSTRAINT FK_5E9E89CB8BAC62AF FOREIGN KEY (city_id) REFERENCES city (id)');
        $this->addSql('ALTER TABLE board ADD CONSTRAINT FK_58562B47B43140E7 FOREIGN KEY (lastthread_id) REFERENCES thread (id)');
        $this->addSql('ALTER TABLE photo_candidate ADD CONSTRAINT FK_C54CD865A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE photo_candidate ADD CONSTRAINT FK_C54CD865302A8A70 FOREIGN KEY (ride_id) REFERENCES ride (id)');
        $this->addSql('ALTER TABLE ride ADD CONSTRAINT FK_9B3D7CD0A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE ride ADD CONSTRAINT FK_9B3D7CD05EC1162 FOREIGN KEY (cycle_id) REFERENCES city_cycle (id)');
        $this->addSql('ALTER TABLE ride ADD CONSTRAINT FK_9B3D7CD08BAC62AF FOREIGN KEY (city_id) REFERENCES city (id)');
        $this->addSql('ALTER TABLE ride ADD CONSTRAINT FK_9B3D7CD04DFE7F82 FOREIGN KEY (featured_photo) REFERENCES photo (id)');
        $this->addSql('ALTER TABLE thread ADD CONSTRAINT FK_31204C83E7EC5785 FOREIGN KEY (board_id) REFERENCES board (id)');
        $this->addSql('ALTER TABLE thread ADD CONSTRAINT FK_31204C838BAC62AF FOREIGN KEY (city_id) REFERENCES city (id)');
        $this->addSql('ALTER TABLE thread ADD CONSTRAINT FK_31204C83524E4EB7 FOREIGN KEY (firstpost_id) REFERENCES post (id)');
        $this->addSql('ALTER TABLE thread ADD CONSTRAINT FK_31204C8338BD6675 FOREIGN KEY (lastpost_id) REFERENCES post (id)');
        $this->addSql('ALTER TABLE city_blocked ADD CONSTRAINT FK_671D55D28BAC62AF FOREIGN KEY (city_id) REFERENCES city (id)');
        $this->addSql('ALTER TABLE track_polyline ADD CONSTRAINT FK_ACF7A6C15ED23C43 FOREIGN KEY (track_id) REFERENCES track (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE track_candidate ADD CONSTRAINT FK_C90A20B0A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE track_candidate ADD CONSTRAINT FK_C90A20B0302A8A70 FOREIGN KEY (ride_id) REFERENCES ride (id)');
        $this->addSql('ALTER TABLE ride_estimate ADD CONSTRAINT FK_ADC7E493A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE ride_estimate ADD CONSTRAINT FK_ADC7E493302A8A70 FOREIGN KEY (ride_id) REFERENCES ride (id)');
        $this->addSql('ALTER TABLE ride_estimate ADD CONSTRAINT FK_ADC7E4935ED23C43 FOREIGN KEY (track_id) REFERENCES track (id)');
        $this->addSql('ALTER TABLE oauth2_authorization_code ADD CONSTRAINT FK_509FEF5FC7440455 FOREIGN KEY (client) REFERENCES oauth2_client (identifier) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE oauth2_refresh_token ADD CONSTRAINT FK_4DD90732B6A2DD68 FOREIGN KEY (access_token) REFERENCES oauth2_access_token (identifier) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE oauth2_access_token ADD CONSTRAINT FK_454D9673C7440455 FOREIGN KEY (client) REFERENCES oauth2_client (identifier) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // Vor der Baseline liegt nichts, worauf sich zurueckrollen liesse: ein
        // funktionierendes down() hiesse hier, die gesamte Datenbank zu
        // loeschen. Wer das wirklich will, nimmt doctrine:schema:drop.
        throw new \LogicException('Die Baseline laesst sich nicht zurueckrollen.');
    }
}
