<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Grundlage für Passkeys: Tabelle für die registrierten Credentials und ein stabiler
 * WebAuthn-User-Handle am Benutzerkonto.
 *
 * Der Handle wird bewusst nicht befüllt. Bestandskonten bekommen ihn beim ersten Kontakt
 * mit WebAuthn, damit diese Migration nicht über die gesamte Nutzertabelle laufen muss.
 *
 * Ersetzt Version20260821113000 aus dem ursprünglichen Passkey-Branch: Die war für MySQL
 * geschrieben (LONGTEXT, AUTO_INCREMENT, Tabelle `user`) und älter als die Baseline. Sie
 * ist nirgends gelaufen; seit dem Umzug auf PostgreSQL heißt die Tabelle `app_user`.
 */
final class Version20261006210000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add webauthn_credential and app_user.webauthnUserHandle for passkeys';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE webauthn_credential (publicKeyCredentialId TEXT NOT NULL, type VARCHAR(255) NOT NULL, transports JSON NOT NULL, attestationType VARCHAR(255) NOT NULL, trustPath JSON NOT NULL, aaguid TEXT NOT NULL, credentialPublicKey TEXT NOT NULL, userHandle VARCHAR(255) NOT NULL, counter INT NOT NULL, otherUI JSON DEFAULT NULL, backupEligible BOOLEAN DEFAULT NULL, backupStatus BOOLEAN DEFAULT NULL, uvInitialized BOOLEAN DEFAULT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, createdAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, lastUsedAt TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_850123F9A76ED395 ON webauthn_credential (user_id)');
        $this->addSql('CREATE INDEX idx_webauthn_user_handle ON webauthn_credential (userHandle)');
        $this->addSql('CREATE UNIQUE INDEX uniq_webauthn_credential_id ON webauthn_credential (publicKeyCredentialId)');
        $this->addSql('ALTER TABLE webauthn_credential ADD CONSTRAINT FK_850123F9A76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE');

        $this->addSql('ALTER TABLE app_user ADD webauthnUserHandle VARCHAR(36) DEFAULT NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_88BDF3E9E74EE973 ON app_user (webauthnUserHandle)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP INDEX UNIQ_88BDF3E9E74EE973');
        $this->addSql('ALTER TABLE app_user DROP webauthnUserHandle');

        $this->addSql('DROP TABLE webauthn_credential');
    }
}
