<?php

namespace App\Application\Sonata\NewsBundle\Entity;

use Sonata\NewsBundle\Entity\BasePostRepository;

/**
 * This file has been generated by the SonataEasyExtendsBundle.
 *
 * @link https://sonata-project.org/easy-extends
 *
 * References:
 * @link http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en#querying:custom-repositories
 * @link http://www.doctrine-project.org/projects/orm/2.0/docs/reference/query-builder/en
 * @link http://www.doctrine-project.org/projects/orm/2.0/docs/reference/dql-doctrine-query-language/en
 */
class PostRepository extends BasePostRepository
{
}
