jms_serializer:
    visitors:
        json_serialization:
            options: 1088 # json_encode options bitmask, suggested JSON_PRETTY_PRINT in development
        json_deserialization:
            options: 1088 # json_decode options bitmask