<?php

namespace App\Application\Sonata\MediaBundle\PHPCR;

use Sonata\MediaBundle\PHPCR\BaseGalleryHasMediaRepository;

/**
 * This file has been generated by the SonataEasyExtendsBundle.
 *
 * @link https://sonata-project.org/easy-extends
 *
 * References :
 * @link http://www.doctrine-project.org/docs/mongodb_odm/1.0/en/reference/query-builder-api.html
 */
class GalleryHasMediaRepository extends BaseGalleryHasMediaRepository
{
}
