caldera_criticalmass_city_show:
    path:  /{citySlug}
    controller: App\Controller\City\CityController::showAction
    options:
        expose: true

caldera_criticalmass_city_listrides:
    path:  /{citySlug}/list
    controller: App\Controller\City\CityController::listRidesAction

caldera_criticalmass_city_missingstats:
    path:  /{citySlug}/missingstats
    controller: App\Controller\City\CityController::missingStatsAction

caldera_criticalmass_city_listgalleries:
    path:  /{citySlug}/galleries
    controller: App\Controller\City\CityController::listGalleriesAction

caldera_criticalmass_city_listtracks:
    path:  /{citySlug}/tracks
    controller: App\Controller\City\CityTrackListController::listTracksAction

caldera_criticalmass_city_locations:
    path:  /{citySlug}/locations
    controller: App\Controller\City\CityController::getlocationsAction
