caldera_criticalmass_gallery_photos_upload_ride:
    path: /{citySlug}/{rideIdentifier}/addphoto
    controller: App\Controller\Photo\PhotoUploadController::uploadAction

caldera_criticalmass_gallery_legacy_photos_upload_ride:
    path: /{citySlug}/{rideIdentifier}/addphoto-legacy
    controller: App\Controller\Photo\LegacyPhotoUploadController::uploadAction
