caldera_criticalmass_photo_user_list:
    path: /photos/list
    controller: App\Controller\Photo\PhotoManagementController::listAction

caldera_criticalmass_photo_manage:
    path: /{citySlug}/{rideIdentifier}/managephotos
    controller: App\Controller\Photo\PhotoManagementController::manageAction

caldera_criticalmass_photo_place_single:
    path: /photo/{id}/place
    controller: App\Controller\Photo\PhotoManagementController::placeSingleAction

caldera_criticalmass_photo_rotate:
    path: /photo/{id}/rotate
    controller: App\Controller\Photo\PhotoManagementController::rotateAction

caldera_criticalmass_photo_toggle:
    path: /photo/{id}/toggle
    controller: App\Controller\Photo\PhotoManagementController::toggleAction

caldera_criticalmass_photo_featured:
    path: /photo/{id}/featured
    controller: App\Controller\Photo\PhotoManagementController::featuredPhotoAction

caldera_criticalmass_photo_delete:
    path: /managephotos/{id}/delete
    controller: App\Controller\Photo\PhotoManagementController::deleteAction

caldera_criticalmass_photo_relocate:
    path: /{citySlug}/{rideIdentifier}/relocatephotos
    controller: App\Controller\Photo\PhotoManagementController::relocateAction

caldera_criticalmass_gallery_photos_rearrange:
    path: /{citySlug}/{rideIdentifier}/gallery/rearrange
    controller: App\Controller\Photo\PhotoManagementController::rearrangeAction

caldera_criticalmass_photo_censor:
    path: /photo/{id}/censor
    controller: App\Controller\Photo\PhotoManagementController::censorAction

caldera_criticalmass_photo_censor_short:
    path: /photo/{id}/censor
    controller: App\Controller\Photo\PhotoManagementController::censorAction
    options:
        expose: true
