caldera_criticalmass_track_delete:
    path:  /track/delete/{trackId}
    controller: App\Controller\Track\TrackManagementController::deleteAction
    options:
        expose: true

caldera_criticalmass_track_toggle:
    path:  /track/toggle/{trackId}
    controller: App\Controller\Track\TrackManagementController::toggleAction

caldera_criticalmass_track_download:
    path:  /track/download/{trackId}
    controller: App\Controller\Track\TrackDownloadController::downloadAction

caldera_criticalmass_track_gpxgenerate:
    path:  /track/generate/{rideId}
    controller: App\Controller\Track\TrackManagementController::gpxgenerateAction

caldera_criticalmass_track_list:
    path:  /track/list
    controller: App\Controller\Track\TrackManagementController::listAction

caldera_criticalmass_track_upload:
    path:  /{citySlug}/{rideIdentifier}/addtrack
    controller: App\Controller\Track\TrackUploadController::uploadAction

caldera_criticalmass_track_view:
    path:  /track/view/{trackId}
    controller: App\Controller\Track\TrackController::viewAction

caldera_criticalmass_track_range:
    path:  /track/range/{trackId}
    controller: App\Controller\Track\TrackRangeController::rangeAction

caldera_criticalmass_track_approve:
    path:  /track/{trackId}/approve
    controller: App\Controller\Track\TrackController::approveAction

caldera_criticalmass_track_time:
    path:  /track/time/{trackId}
    controller: App\Controller\Track\TrackTimeController::timeAction

caldera_criticalmass_track_draw:
    path:  /{citySlug}/{rideIdentifier}/drawtrack
    controller: App\Controller\Track\TrackDrawController::drawAction

caldera_criticalmass_track_edit:
    path:  /track/edit/{trackId}
    controller: App\Controller\Track\TrackManagementController::editAction
