caldera_criticalmass_track_toggle:
    path:  /track/toggle/{id}
    controller: App\Controller\Track\TrackManagementController::toggleAction

caldera_criticalmass_track_download:
    path:  /track/download/{id}
    controller: App\Controller\Track\TrackDownloadController::downloadAction

caldera_criticalmass_track_gpxgenerate:
    path:  /track/generate/{rideId}
    controller: App\Controller\Track\TrackManagementController::gpxgenerateAction

caldera_criticalmass_track_list:
    path:  /track/list
    controller: App\Controller\Track\TrackManagementController::listAction

caldera_criticalmass_track_upload:
    path:  /{citySlug}/{rideIdentifier}/addtrack
    controller: App\Controller\Track\TrackUploadController::uploadAction

caldera_criticalmass_track_view:
    path:  /track/view/{id}
    controller: App\Controller\Track\TrackController::viewAction

caldera_criticalmass_track_range:
    path:  /track/range/{id}
    controller: App\Controller\Track\TrackRangeController::rangeAction

caldera_criticalmass_track_approve:
    path:  /track/{id}/approve
    controller: App\Controller\Track\TrackController::approveAction

caldera_criticalmass_track_time:
    path:  /track/time/{id}
    controller: App\Controller\Track\TrackTimeController::timeAction

caldera_criticalmass_track_draw:
    path:  /{citySlug}/{rideIdentifier}/drawtrack
    controller: App\Controller\Track\TrackDrawController::drawAction

caldera_criticalmass_track_edit:
    path:  /track/edit/{id}
    controller: App\Controller\Track\TrackManagementController::editAction
